import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, BadgeCheck, Boxes, BriefcaseBusiness, Check, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, ClipboardList, Factory, FilePlus2, FileText, Filter, LayoutDashboard, LogOut, Menu, MoreHorizontal, PackageCheck, Plus, Search, Settings2, ShieldCheck, Truck, Users, UserPlus, X } from 'lucide-react';

const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));
const dateLabel = (value) => value ? new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const title = (key) => ({ overview: 'Overview', enquiries: 'Enquiries', quotations: 'Quotations', orders: 'Sales orders' }[key] || 'Overview');
const initialSession = () => { try { return JSON.parse(localStorage.getItem('forgeflow-session')); } catch { return null; } };

function App() {
  const [session, setSession] = useState(initialSession);
  const [page, setPage] = useState('overview');
  const [data, setData] = useState({ dashboard: null, enquiries: [], quotations: [], orders: [], products: [], customers: [] });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [modal, setModal] = useState(null);
  const [customerModalOpen, setCustomerModalOpen] = useState(false);
  const [createdCustomer, setCreatedCustomer] = useState(null);
  const [customerModalError, setCustomerModalError] = useState('');
  const [targetEnquiryId, setTargetEnquiryId] = useState(null);
  const [toast, setToast] = useState('');
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const api = useCallback(async (path, options = {}) => {
    const response = await fetch(`/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(session?.token ? { Authorization: `Bearer ${session.token}` } : {}), ...options.headers } });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.error || 'Something went wrong');
    return body;
  }, [session]);

  const refresh = useCallback(async () => {
    if (!session?.token) return;
    setError('');
    try {
      const [dashboard, enquiries, quotations, orders, products, customers] = await Promise.all(['/dashboard','/enquiries','/quotations','/sales-orders','/products','/customers'].map((path) => api(path)));
      setData({ dashboard, enquiries, quotations, orders, products, customers });
    } catch (cause) { setError(cause.message); }
  }, [session, api]);

  useEffect(() => { refresh(); }, [refresh]);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 3000); return () => clearTimeout(timer); } }, [toast]);

  async function signIn(email, password) {
    setBusy(true); setError('');
    try { const result = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); setSession(result); localStorage.setItem('forgeflow-session', JSON.stringify(result)); }
    catch (cause) { setError(cause.message); }
    finally { setBusy(false); }
  }

  async function act(path, method = 'POST', body) {
    if (path.startsWith('dispatch:')) { setModal({ type: 'dispatch', orderId: path.slice('dispatch:'.length) }); return; }
    setBusy(true); setError('');
    try { await api(path, { method, ...(body ? { body: JSON.stringify(body) } : {}) }); setModal(null); if (path === '/enquiries') setCreatedCustomer(null); setToast('Changes saved successfully'); await refresh(); }
    catch (cause) { setError(cause.message); }
    finally { setBusy(false); }
  }

  async function saveCustomer(body) {
    setBusy(true); setCustomerModalError('');
    try { const customer = await api('/customers', { method: 'POST', body: JSON.stringify(body) }); setCreatedCustomer(customer); setCustomerModalOpen(false); setToast('Customer added to your customer list'); await refresh(); }
    catch (cause) { setCustomerModalError(cause.message); }
    finally { setBusy(false); }
  }
  function logout() { localStorage.removeItem('forgeflow-session'); setSession(null); setData({ dashboard: null, enquiries: [], quotations: [], orders: [], products: [], customers: [] }); }
  const isAdmin = session?.user.role === 'ADMIN';
  const isSales = session?.user.role === 'SALES';

  if (!session?.token) return <Login onSubmit={signIn} busy={busy} error={error} />;
  return <div className="app-shell">
    <aside className={`sidebar ${sidebarOpen ? 'sidebar-open' : ''}`}>
      <div className="brand"><div className="brand-symbol"><Factory size={19} strokeWidth={1.9} /></div><div className="brand-name">forgeflow<span>OPERATIONS</span></div><button className="mobile-close icon-button" onClick={() => setSidebarOpen(false)}><X size={18}/></button></div>
      <div className="workspace-label">WORKSPACE</div>
      <div className="workspace-switch"><span className="workspace-mark">N</span><span className="workspace-text"><b>Northstar Industrial</b><small>Operations team</small></span><ChevronDown size={15}/></div>
      <div className="nav-label">WORKSPACE</div>
      <nav className="primary-nav">
        <NavItem icon={LayoutDashboard} label="Overview" active={page==='overview'} onClick={() => setPage('overview')} />
        <NavItem icon={ClipboardList} label="Enquiries" count={data.enquiries.length} active={page==='enquiries'} onClick={() => setPage('enquiries')} />
        <NavItem icon={FileText} label="Quotations" count={data.quotations.length} active={page==='quotations'} onClick={() => setPage('quotations')} />
        <NavItem icon={BriefcaseBusiness} label="Sales orders" count={data.orders.length} active={page==='orders'} onClick={() => setPage('orders')} />
      </nav>
      <div className="nav-label stock-label">INVENTORY</div>
      <button className="nav-item inventory-nav" onClick={() => setPage('orders')}><Boxes size={17}/><span>Stock availability</span><span className="live-dot"/></button>
      <div className="sidebar-spacer" />
      <div className="help-card"><div className="help-icon"><ShieldCheck size={18}/></div><b>Everything in sync</b><p>Your inventory and orders are up to date.</p><span><i/> System operational</span></div>
      <button className="profile-button" onClick={logout}><div className="avatar">{session.user.name.split(' ').map((part) => part[0]).join('').slice(0,2).toUpperCase()}</div><span className="profile-text"><b>{session.user.name}</b><small>{isAdmin ? 'Administrator' : 'Sales team'}</small></span><LogOut size={16} className="logout-icon"/></button>
    </aside>
    {sidebarOpen && <button className="scrim" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}
    <main className="main-area">
      <header className="topbar"><button className="mobile-menu icon-button" onClick={() => setSidebarOpen(true)}><Menu size={19}/></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14}/><b>{title(page)}</b></div><div className="top-actions"><span className="today">{new Date().toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short',year:'numeric'})}</span><div className="top-divider"/><div className="top-avatar" title={session.user.name}>{session.user.name.split(' ').map((part) => part[0]).join('').slice(0,2).toUpperCase()}</div></div></header>
      <div className="page-content">
        {error && <div className="alert"><CircleAlert size={17}/><span>{error}</span><button onClick={() => setError('')}><X size={15}/></button></div>}
        {page === 'overview' && <Overview dashboard={data.dashboard} orders={data.orders} products={data.products} setPage={setPage} canCreate={isSales} />}
        {page === 'enquiries' && <Enquiries rows={data.enquiries} query={search} setQuery={setSearch} filter={filter} setFilter={setFilter} isSales={isSales} onCreate={() => setModal('enquiry')} onAddCustomer={() => {setCustomerModalError('');setCustomerModalOpen(true);}} onView={(enquiry) => setModal({type:'enquiry-details',enquiry})} onQuote={(enquiry) => { setTargetEnquiryId(enquiry.id); setModal('quotation'); }} />}
        {page === 'quotations' && <Quotations rows={data.quotations} enquiries={data.enquiries} query={search} setQuery={setSearch} filter={filter} setFilter={setFilter} isSales={isSales} isAdmin={isAdmin} onCreate={() => { setTargetEnquiryId(null); setModal('quotation'); }} act={act} busy={busy} />}
        {page === 'orders' && <Orders rows={data.orders} products={data.products} query={search} setQuery={setSearch} filter={filter} setFilter={setFilter} isAdmin={isAdmin} act={act} busy={busy} onAdjust={(product)=>setModal({type:'inventory',product})} />}
      </div>
    </main>
    {modal === 'enquiry' && <EnquiryModal customers={data.customers} products={data.products} createdCustomer={createdCustomer} onAddCustomer={() => {setCustomerModalError('');setCustomerModalOpen(true);}} onClose={() => setModal(null)} onSave={(body) => act('/enquiries','POST',body)} busy={busy}/>}
    {modal === 'quotation' && <QuotationModal enquiries={data.enquiries.filter((item) => !['WON','LOST'].includes(item.status))} products={data.products} initialEnquiryId={targetEnquiryId} onClose={() => setModal(null)} onSave={(body) => act('/quotations','POST',body)} busy={busy}/>}
    {modal?.type === 'enquiry-details' && <EnquiryDetailsModal enquiry={modal.enquiry} api={api} onClose={() => setModal(null)} onQuote={(enquiry) => { setTargetEnquiryId(enquiry.id); setModal('quotation'); }} />}
    {modal?.type === 'dispatch' && <DispatchModal orderId={modal.orderId} api={api} onClose={() => setModal(null)} onSave={(body) => act(`/sales-orders/${modal.orderId}/dispatch`,'POST',body)} busy={busy}/>}
    {modal?.type === 'inventory' && <InventoryModal product={modal.product} onClose={() => setModal(null)} onSave={(quantity) => act(`/inventory/${modal.product.id}`,'PATCH',{physicalQuantity:quantity})} busy={busy}/>}
    {customerModalOpen && <CustomerModal onClose={() => {setCustomerModalOpen(false);setCustomerModalError('');}} onSave={saveCustomer} busy={busy} error={customerModalError}/>}
    {toast && <div className="toast"><Check size={16}/>{toast}</div>}
  </div>;
}

function NavItem({ icon: Icon, label, count, active, onClick }) { return <button className={`nav-item ${active?'active':''}`} onClick={onClick}><Icon size={17}/><span>{label}</span>{count != null && <small>{count}</small>}</button>; }

function Login({ onSubmit, busy, error }) {
  const [email,setEmail] = useState('sales@forgeflow.test'); const [password,setPassword] = useState('Sales123!');
  return <div className="login-page"><section className="login-panel"><div className="login-brand"><div className="brand-symbol"><Factory size={19}/></div><div className="brand-name">forgeflow<span>OPERATIONS</span></div></div><div className="login-main"><div className="eyebrow"><i/> OPERATIONS PLATFORM</div><h1>Good work starts<br/>with a clear view.</h1><p className="login-copy">Manage customer enquiries, quotations and fulfilment in one connected workspace.</p><form className="login-form" onSubmit={(event) => { event.preventDefault(); onSubmit(email,password); }}><label>Work email<input autoComplete="username" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required/></label><label>Password<input autoComplete="current-password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} required/></label>{error && <div className="login-error"><CircleAlert size={15}/>{error}</div>}<button className="button button-primary login-submit" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowRight size={16}/></button></form><div className="demo-note"><ShieldCheck size={15}/><span><b>Demo workspace</b> · Credentials are pre-filled</span></div></div><div className="login-foot"><span>© 2026 forgeflow</span><span>Secure operations, built for industry</span></div></section><section className="login-visual"><div className="visual-grid"/><div className="visual-content"><div className="visual-tag"><span/> SUPPLY CHAIN · LIVE</div><div className="visual-headline">From first enquiry<br/>to <em>out the door.</em></div><p>One clear path from customer request<br/>to delivered order.</p><div className="flow-visual"><FlowStep icon={Users} label="Enquiry" done/><FlowStep icon={FileText} label="Quotation" done/><FlowStep icon={PackageCheck} label="Order" done/><FlowStep icon={Truck} label="Dispatch"/></div></div><div className="visual-foot"><span>BUILT FOR THE WORK THAT MOVES BUSINESS</span><span>01 / 04</span></div><div className="visual-orb orb-one"/><div className="visual-orb orb-two"/></section></div>;
}
function FlowStep({ icon: Icon, label, done }) { return <div className="flow-step"><div className={`flow-icon ${done?'done':''}`}><Icon size={17}/></div><span>{label}</span></div>; }

function PageHeading({ eyebrow, heading, description, action, actionLabel, actionIcon: Icon = Plus, onAction, secondaryActionLabel, secondaryActionIcon: SecondaryIcon = UserPlus, onSecondaryAction }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{heading}</h1><p>{description}</p></div>{(action||secondaryActionLabel)&&<div className="page-heading-actions">{secondaryActionLabel&&<button className="button button-outline" onClick={onSecondaryAction}><SecondaryIcon size={15}/>{secondaryActionLabel}</button>}{action&&<button className="button button-primary" onClick={onAction}><Icon size={16}/>{actionLabel}</button>}</div>}</div>; }
function Overview({ dashboard, orders, products, setPage, canCreate }) {
  const count = dashboard?.counts || {}; const latest = dashboard?.orders || [];
  return <><PageHeading eyebrow={`${new Date().toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).toUpperCase()} · OPERATIONS BRIEF`} heading="Good morning. Here's your overview." description="A live pulse on enquiries, orders and inventory across your operation." action={canCreate} actionLabel="New enquiry" actionIcon={FilePlus2} onAction={() => setPage('enquiries')}/>
    <div className="stat-grid"><StatCard label="Open enquiries" value={count.enquiries ?? '—'} icon={ClipboardList} delta="Across all customers" tone="blue"/><StatCard label="Quotations sent" value={count.quotations ?? '—'} icon={FileText} delta="Total quotations" tone="green"/><StatCard label="Awaiting confirmation" value={count.pending_orders ?? '—'} icon={BriefcaseBusiness} delta="Sales orders pending" tone="sand"/><StatCard label="Ready to dispatch" value={count.to_dispatch ?? '—'} icon={Truck} delta="Confirmed orders" tone="slate"/></div>
    <div className="overview-grid"><section className="panel recent-panel"><PanelHead icon={Activity} title="Recent sales orders" subtitle="Your latest order activity" action="View all" onAction={() => setPage('orders')}/><div className="table-wrap"><table><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>ORDER DATE</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>{latest.length ? latest.slice(0,5).map((row) => <tr key={row.id}><td><b className="mono">{row.order_number}</b></td><td>{row.company_name}</td><td className="muted">{dateLabel(row.order_date)}</td><td className="amount-cell">{money(row.total_amount)}</td><td><Status value={row.status}/></td></tr>) : <EmptyRow columns={5} message="No orders yet — accepted quotations will show up here."/>}</tbody></table></div></section>
    <section className="panel stock-panel"><PanelHead icon={Boxes} title="Stock watch" subtitle="Items with the least available" action="All stock" onAction={() => setPage('orders')}/><div className="stock-list">{(dashboard?.lowStock?.length ? dashboard.lowStock : products.slice(0,5)).slice(0,5).map((item) => { const available = Number(item.available_quantity || 0); const physical = Number(item.physical_quantity || 0); const ratio = physical ? Math.min(100,(available/physical)*100) : 0; return <div className="stock-item" key={item.id}><div className="stock-item-top"><span><b>{item.name}</b><small>{item.product_code}</small></span><strong className={available < 30?'low-number':''}>{available}<small> available</small></strong></div><div className="stock-track"><i style={{width:`${ratio}%`}}/></div></div>; })}{!products.length && !dashboard?.lowStock && <div className="stock-empty">Inventory appears here once connected.</div>}</div></section></div>
    <div className="workflow-strip"><div className="workflow-copy"><span className="workflow-kicker">CONNECTED WORKFLOW</span><b>Every handoff, accounted for.</b><span>Track each customer request from first conversation through fulfilment.</span></div><div className="workflow-steps"><button onClick={() => setPage('enquiries')}><span>01</span>Enquiry<ArrowRight size={14}/></button><button onClick={() => setPage('quotations')}><span>02</span>Quotation<ArrowRight size={14}/></button><button onClick={() => setPage('orders')}><span>03</span>Order<ArrowRight size={14}/></button><button onClick={() => setPage('orders')}><span>04</span>Dispatch<Check size={14}/></button></div></div>
  </>;
}
function StatCard({ label,value,icon:Icon,delta,tone }) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><span className={`stat-icon ${tone}`}><Icon size={17}/></span></div><div className="stat-value">{value}</div><div className="stat-delta"><span>{delta}</span></div></div>; }
function PanelHead({ icon:Icon,title:heading,subtitle,action,onAction }) { return <div className="panel-head"><div className="panel-title-icon"><Icon size={17}/></div><div className="panel-title-copy"><b>{heading}</b><small>{subtitle}</small></div>{action && <button className="text-link" onClick={onAction}>{action}<ArrowRight size={14}/></button>}</div>; }

function Toolbar({ query,setQuery,filter,setFilter,filters }) { return <div className="toolbar"><label className="search-box"><Search size={16}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search by name or number…"/><kbd>⌘ K</kbd></label><div className="filter-control"><Filter size={15}/><select value={filter} onChange={(event)=>setFilter(event.target.value)}>{filters.map((item)=><option key={item}>{item}</option>)}</select><ChevronDown size={14}/></div></div>; }
function Enquiries({ rows,query,setQuery,filter,setFilter,isSales,onCreate,onAddCustomer,onView,onQuote }) {
  const [menuState,setMenuState]=useState(null);
  const menuRef=useRef(null);
  useEffect(()=>{const closeMenu=(event)=>{if(!menuRef.current?.contains(event.target))setMenuState(null);};document.addEventListener('pointerdown',closeMenu);return()=>document.removeEventListener('pointerdown',closeMenu);},[]);
  const filtered = useMemo(()=>rows.filter((row)=>(filter==='All'||row.status===filter)&&(row.enquiry_number+' '+row.company_name+' '+row.contact_person).toLowerCase().includes(query.toLowerCase())),[rows,filter,query]);
  return <><PageHeading eyebrow="SALES PIPELINE" heading="Customer enquiries" description="Capture a customer request and keep every detail moving." action={isSales} actionLabel="New enquiry" actionIcon={Plus} onAction={onCreate} secondaryActionLabel={isSales?'Add customer':undefined} onSecondaryAction={onAddCustomer}/><div className="page-tabs"><button className="selected">All enquiries <span>{rows.length}</span></button><button onClick={()=>setFilter('NEW')}>New <span>{rows.filter((r)=>r.status==='NEW').length}</span></button><button onClick={()=>setFilter('QUOTED')}>Quoted <span>{rows.filter((r)=>r.status==='QUOTED').length}</span></button></div><div className="panel list-panel"><Toolbar query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} filters={['All','NEW','QUOTED','WON','LOST']}/><div className="table-wrap"><table><thead><tr><th>ENQUIRY</th><th>CUSTOMER</th><th>REQUESTED BY</th><th>PRODUCTS</th><th>REQUIRED BY</th><th>STATUS</th><th></th></tr></thead><tbody>{filtered.length?filtered.map((row)=><tr key={row.id}><td><b className="mono">{row.enquiry_number}</b><small className="cell-sub">Received {dateLabel(row.enquiry_date)}</small></td><td><b>{row.company_name}</b><small className="cell-sub">{row.city}</small></td><td>{row.contact_person}</td><td><span className="number-pill">{row.product_count} items · {row.units} units</span></td><td>{dateLabel(row.required_date)}</td><td><Status value={row.status}/></td><td><div className="enquiry-actions" ref={menuState?.id===row.id?menuRef:null}><button className="icon-button row-more" title="Enquiry actions" aria-label={`Actions for ${row.enquiry_number}`} aria-haspopup="menu" aria-expanded={menuState?.id===row.id} onClick={(event)=>{if(menuState?.id===row.id){setMenuState(null);return;}const rect=event.currentTarget.getBoundingClientRect();setMenuState({id:row.id,top:Math.min(rect.bottom+4,window.innerHeight-90),left:Math.max(8,Math.min(rect.right-166,window.innerWidth-174))});}}><MoreHorizontal size={17}/></button>{menuState?.id===row.id&&<div className="enquiry-menu" role="menu" style={{top:menuState.top,left:menuState.left}}><button role="menuitem" onClick={()=>{setMenuState(null);onView(row);}}>View details</button>{isSales&&!['WON','LOST'].includes(row.status)&&<button role="menuitem" onClick={()=>{setMenuState(null);onQuote(row);}}>Create quotation</button>}</div>}</div></td></tr>):<EmptyRow columns={7} message={query?'No enquiries match your search.':'No enquiries yet. Start with the first customer request.'} />}</tbody></table></div><div className="table-foot"><span>Showing <b>{filtered.length?1:0}–{filtered.length}</b> of {filtered.length} enquiries</span><div><button disabled><ChevronLeft size={15}/></button><button disabled><ChevronRight size={15}/></button></div></div></div></>;
}
function Quotations({ rows,enquiries,query,setQuery,filter,setFilter,isSales,isAdmin,onCreate,act,busy }) {
  const filtered=useMemo(()=>rows.filter((row)=>(filter==='All'||row.status===filter)&&(row.quotation_number+' '+row.company_name+' '+row.enquiry_number).toLowerCase().includes(query.toLowerCase())),[rows,filter,query]);
  return <><PageHeading eyebrow="PRICING & PROPOSALS" heading="Quotations" description="Sales submits each offer for admin review. Accepted quotations can then be converted into orders." action={isSales&&enquiries.length>0} actionLabel="New quotation" actionIcon={Plus} onAction={onCreate}/><div className="page-tabs"><button className="selected">All quotations <span>{rows.length}</span></button>{['DRAFT','SENT','ACCEPTED','REJECTED'].map((status)=><button key={status} onClick={()=>setFilter(status)}>{status.charAt(0)+status.slice(1).toLowerCase()} <span>{rows.filter((r)=>r.status===status).length}</span></button>)}</div><div className="panel list-panel"><Toolbar query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} filters={['All','DRAFT','SENT','ACCEPTED','REJECTED']}/><div className="table-wrap"><table><thead><tr><th>QUOTATION</th><th>CUSTOMER / ENQUIRY</th><th>VALID UNTIL</th><th>ITEMS</th><th>GRAND TOTAL</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{filtered.length?filtered.map((row)=><tr key={row.id}><td><b className="mono">{row.quotation_number}</b><small className="cell-sub">Created {dateLabel(row.created_at)}</small></td><td><b>{row.company_name}</b><small className="cell-sub">{row.enquiry_number}</small></td><td>{dateLabel(row.valid_until)}</td><td>{row.product_count} items</td><td className="amount-cell">{money(row.grand_total)}</td><td><Status value={row.status}/></td><td><div className="row-actions">{isSales&&row.status==='DRAFT'&&<button className="small-action" disabled={busy} onClick={()=>act(`/quotations/${row.id}/status`,'PATCH',{status:'SENT'})}>Send to admin</button>}{isAdmin&&row.status==='SENT'&&<><button className="small-action" disabled={busy} onClick={()=>act(`/quotations/${row.id}/status`,'PATCH',{status:'ACCEPTED'})}>Accept</button><button className="small-action quiet-action" disabled={busy} onClick={()=>act(`/quotations/${row.id}/status`,'PATCH',{status:'REJECTED'})}>Reject</button></>}{isSales&&row.status==='SENT'&&<span className="role-note">Awaiting admin review</span>}{isSales&&row.status==='ACCEPTED'&&<button className="small-action" disabled={busy} onClick={()=>act(`/quotations/${row.id}/convert`)}>Create order <ArrowRight size={13}/></button>}{isAdmin&&row.status==='ACCEPTED'&&<span className="role-note">Awaiting sales order</span>}{isAdmin&&row.status==='DRAFT'&&<span className="role-note">Awaiting sales submission</span>}</div></td></tr>):<EmptyRow columns={7} message={query?'No quotations match your search.':'Create a quotation from a customer enquiry.'}/>}</tbody></table></div><div className="table-foot"><span>{filtered.length} quotation{filtered.length===1?'':'s'}</span><span>Totals calculated by the server · INR</span></div></div>{isSales&&!enquiries.length&&<div className="inline-hint"><CircleAlert size={16}/>Create an enquiry before you prepare a quotation.</div>}</>;
}
function Orders({ rows,products,query,setQuery,filter,setFilter,isAdmin,act,busy,onAdjust }) {
  const filtered=useMemo(()=>rows.filter((row)=>(filter==='All'||row.status===filter)&&(row.order_number+' '+row.company_name+' '+row.quotation_number).toLowerCase().includes(query.toLowerCase())),[rows,filter,query]);
  return <><PageHeading eyebrow="ORDER MANAGEMENT" heading="Sales orders" description="Confirm available stock, reserve it, then close the loop with dispatch."/><div className="inventory-overview"><div className="inventory-overview-title"><span className="stat-icon green"><Boxes size={17}/></span><div><b>Inventory availability</b><small>Available = physical quantity − reserved quantity</small></div></div><div className="inventory-chips">{products.map((product)=><div className="inventory-chip" key={product.id}><span>{product.name}</span><b className={Number(product.available_quantity)<30?'low-number':''}>{product.available_quantity} <small>{product.unit}</small></b>{isAdmin&&<button className="inventory-adjust" onClick={()=>onAdjust(product)}>Adjust stock</button>}</div>)}</div></div><div className="page-tabs"><button className="selected">All orders <span>{rows.length}</span></button>{['PENDING','CONFIRMED','DISPATCHED','CANCELLED'].map((status)=><button key={status} onClick={()=>setFilter(status)}>{status.charAt(0)+status.slice(1).toLowerCase()} <span>{rows.filter((r)=>r.status===status).length}</span></button>)}</div><div className="panel list-panel"><Toolbar query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} filters={['All','PENDING','CONFIRMED','DISPATCHED','CANCELLED']}/><div className="table-wrap"><table><thead><tr><th>ORDER</th><th>CUSTOMER / QUOTATION</th><th>DATE</th><th>PRODUCTS</th><th>TOTAL</th><th>STATUS</th><th>NEXT STEP</th></tr></thead><tbody>{filtered.length?filtered.map((row)=><tr key={row.id}><td><b className="mono">{row.order_number}</b></td><td><b>{row.company_name}</b><small className="cell-sub">{row.quotation_number}</small></td><td>{dateLabel(row.order_date)}</td><td>{row.product_count} items · {row.units} units</td><td className="amount-cell">{money(row.total_amount)}</td><td><Status value={row.status}/></td><td>{row.status==='PENDING'&&isAdmin?<button className="small-action" disabled={busy} onClick={()=>act(`/sales-orders/${row.id}/confirm`)}>Confirm & reserve</button>:row.status==='CONFIRMED'&&isAdmin?<button className="small-action dispatch-action" disabled={busy} onClick={()=>act('dispatch:'+row.id)}>Process dispatch <ArrowRight size={13}/></button>:row.status==='PENDING'?<span className="role-note">Admin confirms</span>:row.status==='CONFIRMED'?<span className="role-note">Ready to dispatch</span>:row.status==='DISPATCHED'?<span className="done-note"><Check size={13}/>Complete</span>:<span className="role-note">—</span>}</td></tr>):<EmptyRow columns={7} message={query?'No sales orders match your search.':'Accepted quotations become sales orders here.'}/>}</tbody></table></div><div className="table-foot"><span>{filtered.length} sales order{filtered.length===1?'':'s'}</span><span>Reservation and dispatch are transactional</span></div></div>{isAdmin&&<p className="role-hint"><ShieldCheck size={15}/> Admin access is required to confirm orders and process dispatch.</p>}</>;
}
function Status({ value }) { const styles={NEW:'status-blue',QUOTED:'status-teal',WON:'status-green',LOST:'status-muted',DRAFT:'status-muted',SENT:'status-blue',ACCEPTED:'status-green',REJECTED:'status-red',PENDING:'status-amber',CONFIRMED:'status-teal',DISPATCHED:'status-green',CANCELLED:'status-muted'}; return <span className={`status ${styles[value]||'status-muted'}`}><i/>{value?.charAt(0)+value?.slice(1).toLowerCase()}</span>; }
function EmptyRow({ columns,message }) { return <tr><td colSpan={columns}><div className="empty-state"><span><ClipboardList size={19}/></span>{message}</div></td></tr>; }

function Modal({ title:heading,description,onClose,children,onSave,busy,saveLabel='Save',showSave=true,closeLabel='Cancel' }) { return <div className="modal-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><form className="modal" onSubmit={(event)=>{event.preventDefault();onSave();}}><div className="modal-head"><div><h2>{heading}</h2><p>{description}</p></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="modal-body">{children}</div><div className="modal-foot"><button type="button" className="button button-outline" onClick={onClose}>{closeLabel}</button>{showSave&&<button className="button button-primary" disabled={busy}>{busy?'Saving…':saveLabel}<ArrowRight size={15}/></button>}</div></form></div>; }
function EnquiryModal({ customers,products,createdCustomer,onAddCustomer,onClose,onSave,busy }) {
  const [customerId,setCustomerId]=useState(customers[0]?.id||''); const [requiredDate,setRequiredDate]=useState(''); const [notes,setNotes]=useState(''); const [productId,setProduct]=useState(products[0]?.id||''); const [quantity,setQuantity]=useState(1); const [items,setItems]=useState([]);
  const selectedCustomer=customers.find((customer)=>customer.id===customerId); const selected=products.find((product)=>product.id===productId);
  useEffect(()=>{if(createdCustomer?.id)setCustomerId(createdCustomer.id);},[createdCustomer]);
  return <Modal title="New customer enquiry" description="Choose a customer from your saved records and add the requested products." onClose={onClose} onSave={()=>onSave({customerId,requiredDate:requiredDate||undefined,notes,items})} busy={busy} saveLabel="Create enquiry"><div className="form-section-title">CUSTOMER</div><div className="customer-picker-row"><Field label="Select customer"><select required value={customerId} onChange={(event)=>setCustomerId(event.target.value)}><option value="">Choose a customer…</option>{customers.map((customer)=><option value={customer.id} key={customer.id}>{customer.company_name} · {customer.contact_person}</option>)}</select></Field><button type="button" className="button button-outline customer-picker-add" onClick={onAddCustomer}><UserPlus size={14}/>Add customer</button></div>{selectedCustomer?<div className="customer-preview"><b>{selectedCustomer.contact_person}</b><span>{selectedCustomer.email}</span><span>{selectedCustomer.mobile}</span><span>{selectedCustomer.city}</span></div>:!customers.length?<div className="empty-inline">Your customer list is empty. Add a customer to continue.</div>:null}<div className="form-grid"><Field label="Required by"><input type="date" value={requiredDate} onChange={(event)=>setRequiredDate(event.target.value)}/></Field><Field label="Notes"><input value={notes} onChange={(event)=>setNotes(event.target.value)} placeholder="Specifications or delivery notes"/></Field></div><div className="form-section-title product-section-title">PRODUCTS REQUESTED</div><div className="item-add-row"><select value={productId} onChange={(event)=>setProduct(event.target.value)}>{products.map((product)=><option value={product.id} key={product.id}>{product.product_code} · {product.name}</option>)}</select><input type="number" min="1" value={quantity} onChange={(event)=>setQuantity(Number(event.target.value))}/><button type="button" className="button button-outline" disabled={!selected||items.some((item)=>item.productId===productId)} onClick={()=>{setItems([...items,{productId,quantity}]);setQuantity(1);}}><Plus size={14}/>Add</button></div><div className="selected-lines">{items.map((item)=><div key={item.productId}><span>{products.find((product)=>product.id===item.productId)?.name}</span><b>{item.quantity} units</b><button type="button" onClick={()=>setItems(items.filter((line)=>line.productId!==item.productId))}><X size={14}/></button></div>)}{!items.length&&<small>Select one or more products to continue.</small>}</div></Modal>;
}
function CustomerModal({ onClose,onSave,busy,error }) {
  const [companyName,setCompany]=useState(''); const [contactPerson,setContact]=useState(''); const [mobile,setMobile]=useState(''); const [email,setEmail]=useState(''); const [city,setCity]=useState('');
  return <Modal title="Add customer" description="Save a customer once, then select them for future enquiries." onClose={onClose} onSave={()=>onSave({companyName,contactPerson,mobile,email,city})} busy={busy} saveLabel="Save customer"><div className="form-grid"><Field label="Company name"><input required maxLength="200" value={companyName} onChange={(event)=>setCompany(event.target.value)} placeholder="e.g. Northstar Engineering"/></Field><Field label="Contact person"><input required maxLength="120" value={contactPerson} onChange={(event)=>setContact(event.target.value)} placeholder="Full name"/></Field><Field label="Mobile"><input required maxLength="40" value={mobile} onChange={(event)=>setMobile(event.target.value)} placeholder="+91 98xxx xxxxx"/></Field><Field label="Email"><input required type="email" maxLength="254" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="name@company.com"/></Field><Field label="City"><input required maxLength="120" value={city} onChange={(event)=>setCity(event.target.value)} placeholder="City"/></Field></div>{error&&<div className="login-error"><CircleAlert size={15}/>{error}</div>}</Modal>;
}
function QuotationModal({ enquiries,products,initialEnquiryId,onClose,onSave,busy }) {
  const [enquiryId,setEnquiry]=useState(initialEnquiryId||enquiries[0]?.id||''); const [validUntil,setValid]=useState(''); const [items,setItems]=useState([]);
  const enquiry=enquiries.find((item)=>item.id===enquiryId);
  useEffect(()=>{ if(!enquiryId)return; fetch(`/api/enquiries/${enquiryId}/items`,{headers:{Authorization:`Bearer ${initialSession()?.token||''}`}}).then((response)=>response.ok?response.json():[]).then((result)=>setItems(Array.isArray(result)?result.map((item)=>({productId:item.product_id,quantity:item.quantity,unitPrice:Number(products.find((product)=>product.id===item.product_id)?.base_price||0),discountPct:0,gstPct:18})):[])).catch(()=>setItems([])); },[enquiryId,enquiries,products]);
  return <Modal title="Prepare quotation" description="Price enquiry products. Line totals and GST are validated by the server." onClose={onClose} onSave={()=>onSave({enquiryId,validUntil,items})} busy={busy} saveLabel="Create quotation"><Field label="Customer enquiry"><select required value={enquiryId} onChange={(e)=>setEnquiry(e.target.value)}>{enquiries.map((item)=><option key={item.id} value={item.id}>{item.enquiry_number} · {item.company_name}</option>)}</select></Field><div className="quotation-context"><FileText size={16}/><span>{enquiry?.product_count||0} requested products · {enquiry?.units||0} units</span><span>{enquiry?.required_date?`Needed by ${dateLabel(enquiry.required_date)}`:'No required date'}</span></div><Field label="Valid until"><input type="date" required value={validUntil} onChange={(e)=>setValid(e.target.value)}/></Field><div className="form-section-title product-section-title">PRICE EACH LINE</div>{items.map((item,index)=><div className="quote-line" key={item.productId}><span>{products.find((product)=>product.id===item.productId)?.name}<small>{item.quantity} units</small></span><label><small>PRICE / UNIT</small><input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(e)=>setItems(items.map((line,i)=>i===index?{...line,unitPrice:Number(e.target.value)}:line))}/></label><label><small>DISCOUNT %</small><input type="number" min="0" max="100" step="0.1" value={item.discountPct} onChange={(e)=>setItems(items.map((line,i)=>i===index?{...line,discountPct:Number(e.target.value)}:line))}/></label><label><small>GST %</small><input type="number" min="0" max="100" step="0.1" value={item.gstPct} onChange={(e)=>setItems(items.map((line,i)=>i===index?{...line,gstPct:Number(e.target.value)}:line))}/></label></div>)}{!items.length&&<div className="empty-inline">No products are available for this enquiry. If it was just created, refresh and reopen.</div>}</Modal>;
}
function EnquiryDetailsModal({ enquiry,api,onClose,onQuote }) {
  const [detail,setDetail]=useState(null);
  const [items,setItems]=useState([]);
  const [error,setError]=useState('');
  useEffect(()=>{Promise.all([api(`/enquiries/${enquiry.id}`),api(`/enquiries/${enquiry.id}/items`)]).then(([head,lines])=>{setDetail(head);setItems(lines);}).catch((cause)=>setError(cause.message));},[api,enquiry.id]);
  const canQuote=!['WON','LOST'].includes(enquiry.status);
  return <Modal title={enquiry.enquiry_number} description="Customer request details and requested product lines." onClose={onClose} onSave={()=>onQuote(enquiry)} showSave={canQuote} closeLabel="Close" saveLabel="Create quotation"><div className="enquiry-detail-grid"><div><small>CUSTOMER</small><b>{detail?.company_name||enquiry.company_name}</b></div><div><small>CONTACT PERSON</small><b>{detail?.contact_person||enquiry.contact_person}</b></div><div><small>EMAIL</small><b>{detail?.email||'—'}</b></div><div><small>MOBILE</small><b>{detail?.mobile||'—'}</b></div><div><small>CITY</small><b>{detail?.city||enquiry.city||'—'}</b></div><div><small>REQUIRED BY</small><b>{dateLabel(detail?.required_date||enquiry.required_date)}</b></div></div>{error&&<div className="inline-hint"><CircleAlert size={15}/>{error}</div>}<div className="form-section-title product-section-title">REQUESTED PRODUCTS</div><div className="enquiry-detail-lines">{items.map((item)=><div key={item.product_id}><span><b>{item.name}</b><small>{item.product_code} · {item.unit}</small></span><strong>{item.quantity} units</strong></div>)}{!items.length&&!error&&<small className="detail-loading">Loading enquiry products…</small>}</div>{detail?.notes&&<div className="enquiry-notes"><small>NOTES</small><p>{detail.notes}</p></div>}<div className="detail-status">Current status <Status value={enquiry.status}/></div></Modal>;
}

function DispatchModal({ orderId,api,onClose,onSave,busy }) {
  const [order,setOrder]=useState(null); const [vehicleNumber,setVehicle]=useState(''); const [driverName,setDriver]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{api(`/sales-orders/${orderId}`).then(setOrder).catch((cause)=>setError(cause.message));},[api,orderId]);
  return <Modal title="Process dispatch" description="The dispatch consumes reserved stock and closes the sales order." onClose={onClose} onSave={()=>onSave({vehicleNumber,driverName})} busy={busy} saveLabel="Confirm dispatch"><div className="dispatch-summary"><div><small>SALES ORDER</small><b>{order?.order_number||'Loading order…'}</b></div><div><small>CUSTOMER</small><b>{order?.company_name||'—'}</b></div><div><small>ORDER TOTAL</small><b>{money(order?.total_amount)}</b></div></div>{error&&<div className="inline-hint"><CircleAlert size={15}/>{error}</div>}<div className="form-section-title product-section-title">RESERVED PRODUCTS TO DISPATCH</div><div className="dispatch-lines">{order?.items?.map((item)=><div key={item.id}><span><b>{item.name}</b><small>{item.product_code} · {item.reserved_quantity} reserved</small></span><b>{item.quantity} <small>{item.unit}</small></b></div>)}</div><div className="form-grid"><Field label="Vehicle number"><input required value={vehicleNumber} onChange={(e)=>setVehicle(e.target.value)} placeholder="e.g. MH 12 AB 3456"/></Field><Field label="Driver name"><input required value={driverName} onChange={(e)=>setDriver(e.target.value)} placeholder="Full name"/></Field></div></Modal>;
}
function InventoryModal({ product,onClose,onSave,busy }) {
  const [quantity,setQuantity]=useState(Number(product.physical_quantity)); const reserved=Number(product.reserved_quantity);
  return <Modal title="Adjust physical stock" description="Available stock is recalculated from physical quantity less reservations." onClose={onClose} onSave={()=>onSave(quantity)} busy={busy} saveLabel="Save adjustment"><div className="dispatch-summary"><div><small>PRODUCT</small><b>{product.name}</b></div><div><small>RESERVED</small><b>{reserved} {product.unit}</b></div><div><small>AVAILABLE NOW</small><b>{product.available_quantity} {product.unit}</b></div></div><Field label="New physical quantity"><input type="number" min={reserved} step="1" value={quantity} onChange={(event)=>setQuantity(Number(event.target.value))}/></Field><div className="inline-hint"><ShieldCheck size={15}/>Stock cannot be set below the {reserved} units already reserved. The server checks this again when saving.</div></Modal>;
}
function Field({ label,children }) { return <label className="field"><span>{label}</span>{children}</label>; }

export default App;
